# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Accueil |
    url: '/'
    weight: 10
  - name: Programme |
    url: '#programme'
    weight: 20
  - name: Intervenants |
    url: '#people'
    weight: 30
  - name: Séquences |
    url: '/sequences/'
    weight: 40
    identifier: sequences
  - name: "Toutes les séquences"
    url: '/sequences/'
    weight: 40
    parent: sequences
  - name: "Concepts"
    url: '/sequences/concepts/'
    weight: 40
    parent: sequences
  - name: "Tour d'horizon"
    url: '/sequences/illustrations/'
    weight: 40
    parent: sequences
  - name: À propos
    url: '#about'
    weight: 60
